# Generated by Django 5.2.6 on 2025-10-17 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_hall_remove_movie_image_movie_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='capacity',
        ),
        migrations.AddField(
            model_name='hall',
            name='rows',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='hall',
            name='seats_per_row',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=2)),
                ('number', models.PositiveIntegerField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.hall')),
            ],
            options={
                'ordering': ['row', 'number'],
                'unique_together': {('hall', 'row', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.showtime')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.seat')),
            ],
            options={
                'unique_together': {('showtime', 'seat')},
            },
        ),
    ]
