version: "3.9"

services:
  db:
    image: postgres:15
    container_name: moviedb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - moviedb:/var/lib/postgresql/data

  web:
    build:
        context: ./movie_reservation_system
        dockerfile: Dockerfile
    container_name: movieapp
    volumes:
      - ./movie_reservation_system:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  nginx:
        image: nginx:latest
        container_name: movie_nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - static_volume:/app/movie_reservation_system/staticfiles
            - media_volume:/app/movie_reservation_system/media
        depends_on:
            - web

volumes:
  moviedb:
  static_volume:
  media_volume:
